//this.createDialog = (scene, x, y, scenarioText, zone, buttonText1, buttonText2, nextScenario1, nextScenario2, end)

const scenarioTree = {
	//Dialog with NPC in village, needs Netflix ideas, this.createDialog = (scene, x, y, scenarioText, zone, buttonText1, buttonText2, nextScenario1, nextScenario2, end)
	'startVillageNPC': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "SAM: I'm sorry Jim but I'm recinding your promotion. You cannot be cohort lead.", zone, 'Why??', '', 'notFriends', null, false).setScrollFactor(0) },
	'notFriends': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "SAM: We're just not good enough friends. If you're not in my top 8 friends on myspace, you can't be in the top 8 people in the classroom team ", zone, 'What can I do?', '', 'continueSam', null, false).setScrollFactor(0) },
	'continueSam': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "SAM: I don't know Jim. Is there anything you can do that would make me like you better than Xav?", zone, 'Talk about Drag Race', 'Talk about Corbyn', 'dragRace', 'corbyn', false).setScrollFactor(0) },
	'corbyn': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "SAM: Way to remind me about Starmer, Jim. We will never reach the dizzying heights of 2019 again.", zone, "Tell him he's great at Flutter", 'Sing him a bespoke sea shanty', 'flutter', 'seaShanty', false).setScrollFactor(0) },
	'dragRace': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "SAM: Eh, I'm over Drag Race now. Too much rigor morris. Dragula is where it's at now.", zone, "Tell him he's great at Flutter", 'Sing him a bespoke sea shanty', 'flutter', 'seaShanty', false).setScrollFactor(0) },
	'flutter': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "SAM: Urgh, flattery. Try again later.", zone, 'continue', '', null, null, false).setScrollFactor(0) },
	'seaShanty': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "SAM starts swaying to your dulcet tones. SAM: Wow! What a stirring tune! I misjudged you Jim. Very well, I'll sign the approval paperwork.", zone, 'continue', '', 'shirt', null, false).setScrollFactor(0) },
	'shirt': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "Whilst SAM is distracted, you take the opportunity to steal his BEST PLAID SHIRT and continue on your way", zone, 'continue', '', null, null, true).setScrollFactor(0) },

	//Dialog with NPC in wood, sad and needs someone to listen, this.createDialog = (scene, x, y, scenarioText, zone, buttonText1, buttonText2, nextScenario1, nextScenario2, end)
	'startWoodNPC': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "JONNY: Jim! There you are! I was just telling Vel you can't take up the cohort lead role yet. Passport isn't finished and we need you to get it ready for release.", zone, "But I don't work on internal dev anymore", "", 'internalDev', null, false).setScrollFactor(0) },
	'internalDev': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "JONNY: I'm sorry Jim, we don't have time for this unproductive talk. Please just get coding", zone, 'Code in silence', "", 'silentCode', null, false).setScrollFactor(0) },
	'silentCode': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "exports.getGroups = await (user, scopes) {...", zone, 'Continue coding in silence', "Ask about Jonny's weekend", 'continueSilence', 'weekend', false).setScrollFactor(0) },
	'continueSilence': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "...axios.get({if(scopes.includes(learn:READ)){...", zone, 'Continue coding in silence', "Ask about Jonny's band", 'continueSilence2', 'band', false).setScrollFactor(0) },
	'weekend': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "JONNY gives you a hard stare", zone, 'Continue coding in silence', '', 'continueSilence', null, false).setScrollFactor(0) },
	'band': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "JONNY gives you a hard stare", zone, 'Continue coding in silence', '', 'continueSilence2', null, false).setScrollFactor(0) },
	'continueSilence2': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "...if(ncauth){fetchGroups(user.email)...", zone, 'Continue coding in silence', "Marry Jonny's sister", 'continueSilence3', 'marriage', false).setScrollFactor(0) },
	'continueSilence3': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "...}})} git add . git commit -m 'add groups controller'", zone, 'git push main', '', 'gitPush', null, false).setScrollFactor(0) },
	'gitPush': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "JONNY: Thanks Jim! Assuming it passes the pipeline, I'll withdraw my objections", zone, 'continue', '', 'lego', null, false).setScrollFactor(0) },
	'marriage': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "Dammit Jim! You know I can't refuse a request from a relative! Fine, I'll withdraw my objections.", zone, 'continue', '', 'lego', null, false).setScrollFactor(0) },
	'lego': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "JONNY pulls a small box from his pocket and ceremonially hands you a SMALL LEGO FIGURE before waving you on your way", zone, 'continue', '', null, null, true).setScrollFactor(0) },

	//Dialog with NPC in park, needs date ideas, this.createDialog = (scene, x, y, scenarioText, zone, buttonText1, buttonText2, nextScenario1, nextScenario2, end)
	'startParkNPC': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "PAUL C: Hello Jim! Obviously I'm really excited to be working with you! But I did just have a couple of concerns about your coding skills!", zone, 'But... I just conquered my imposter syndrome', "", 'imposter', null, false).setScrollFactor(0) },
	'imposter': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "PAUL C: Haha! Yes, very well done! But you don't mind if I reactivate it by testing you on a few coding questions, do you?", zone, "I guess...", "", 'adventIntro', null, false).setScrollFactor(0) },
	'adventIntro': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "PAUL C: What would you use to find the position of a bunch of crabs in submarines?", zone, "a grid", "tail call recursion", 'grid1', 'wrongAnswer', false).setScrollFactor(0) },
	'wrongAnswer': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "PAUL C: Oooh, no. I guess you really are an imposter! Do you want to try again?", zone, "continue", '', null, null, false).setScrollFactor(0) },
	'grid1': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "PAUL C: Haha, obviously! Next question: what would you use to track the reproductive cycle of lantern fish?", zone, "a grid", 'tail call recursion', 'wrongAnswer', 'recursion1', false).setScrollFactor(0) },
	'recursion1': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "PAUL C: Haha, of course! Next question: what's the right way to work out the energy levels of octopuses?", zone, "a grid", 'tail call recursion', 'grid2', 'wrongAnswer', false).setScrollFactor(0) },
	'grid2': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "PAUL C: Always the grid, eh! Final question: what's the best way to navigate through a cave of molluscs", zone, "tail call recursion", 'A* pathfinding', 'wrongAnswer', 'pathfinding', false).setScrollFactor(0) },
	'pathfinding': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "PAUL C: How could I ever have doubted your skills!", zone, "continue", '', 'calendar', null, false).setScrollFactor(0) },
	'calendar': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "PAUL C shakes your hand and sends you on your way. He gives you AN ADVENT CALENDAR", zone, "continue", '', null, null, true).setScrollFactor(0) },

	//Dialog with NPC in supermarket, overwhelmed by choice of pasta, this.createDialog = (scene, x, y, scenarioText, zone, buttonText1, buttonText2, nextScenario1, nextScenario2, end)	
	'startSupermarketNPC': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "LISA: Oh Jim, I'm so pleased I ran into you! There's an apprenticeships emergency", zone, "What is it?", '', 'bowlerEggs', null, false).setScrollFactor(0) },
	'bowlerEggs': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "LISA: Bowler Eggs just called. Justin still can't write a single line of Typescript. You need to fix this.", zone, "teach JUSTIN TypeScript", 'distract LISA with your feminine wiles', 'typescript', 'highHeels', false).setScrollFactor(0) },
	'typescript': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "LISA: Sorry Jim, you're pitching it too high. Justin's totally lost. Can you step it down a bit?", zone, "Teach JUSTIN JavaScript", "", 'javaScript', null, false).setScrollFactor(0) },
	'javaScript': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "LISA: Sorry Jim, you're pitching it too high. Justin's totally lost. Can you step it down a bit?", zone, "Teach JUSTIN coding fundamentals", "", 'fundamentals', null, false).setScrollFactor(0) },
	'fundamentals': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "LISA: Thanks Jim, I think he's got it now. Oh hang on, the phone's just ringing, let me see who it is...", zone, "continue", "", 'bowlerEggs', null, false).setScrollFactor(0) },
	'highHeels': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "You slip on a pair of high heels. LISA is dazzled by your dance moves. You sashay away before she can recover", zone, "continue", "", 'highHeels2', null, false).setScrollFactor(0) },
	'highHeels2': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "You have gained A PAIR OF HIGH HEELS", zone, "continue", "", null, null, true).setScrollFactor(0) },

	//Dialog with NPC in old forest, lonely and needs a chat, this.createDialog = (scene, x, y, scenarioText, zone, buttonText1, buttonText2, nextScenario1, nextScenario2, end)
	'startOldForestNPC': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "SARAH: Oh hey Jim! Are you busy?", zone, "Yeah, I'm just on my way to become cohort lead", '', 'walk', null, false).setScrollFactor(0) },
	'walk': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "SARAH: Oh cool, I'll walk with you. Did I tell you the tragic story of my awful sister yet?", zone, "Actually you already did and I'm just on my way...", "", 'chat1', '', false).setScrollFactor(0) },
	'chat1': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "SARAH: No worries, I won't bother you. Say, what are you up to this weekend?", zone, 'Uh, nothing much...', "", 'chat2', null, false).setScrollFactor(0) },
	'chat2': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "SARAH: Oh fun! Guess what I'm up to!", zone, "I don't know", "", 'chat3', null, false).setScrollFactor(0) },
	'chat3': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "SARAH: So close! I'm actually going morris dancing in an ancient cave with a bunch of people from Oxford", zone, "That sounds nice but I've actually got to go...", "", 'chat4', null, false).setScrollFactor(0) },
	'chat4': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "SARAH: Of course, I won't stop you. Where are you going to?", zone, "Like I said, I'm on my way to become cohort lead", "Hey, do you want to become monarch of some goblins", 'walk', 'crown', false).setScrollFactor(0) },
	'crown': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "SARAH: Ohhhh, a crown... Subjects... I must go and attend to my kingdom!", zone, 'continue', "", 'crownend', null, false).setScrollFactor(0) },
	'crownend': function (zone) { this.createDialog(this, 2243.10344827586, 4050, "SARAH runs off leaving you holding a GOBLIN CROWN OF BENT FORKS", zone, 'continue', "", null, null, true).setScrollFactor(0) },

	//Dialog with NPC in graveyard, needs a job, this.createDialog = (scene, x, y, scenarioText, zone, buttonText1, buttonText2, nextScenario1, nextScenario2, end)
	'startGraveyardNPC': function (zone) { this.createDialog(this, 2243.10344827586, 4050, 'JATINDER: Jim, you have changed my life', zone, "I'm sure I didn't", "", "changeLife", null, false).setScrollFactor(0) },
	"changeLife": function (zone) { this.createDialog(this, 2243.10344827586, 4050, "You did! Without you I would never have made it through the bootcamp", zone, 'Why yes, I am the best', "Oh no, I didn't do anything special", "thanks", 'demure', false).setScrollFactor(0) },
	"demure": function (zone) { this.createDialog(this, 2243.10344827586, 4050, "Nothing special? Your fascinating lecture examples were the only reason I learned anything about code. You are a master teacher", zone, 'Why yes, I am the best', "I am no better than anyone else", "thanks", 'demure2', false).setScrollFactor(0) },
	"demure2": function (zone) { this.createDialog(this, 2243.10344827586, 4050, "As if! No, only you have the special gift of being a man of the people. Your comforting presence made every day a joy", zone, 'Why yes, I am the best', "It's literally nothing", "thanks", 'demure3', false).setScrollFactor(0) },
	"demure3": function (zone) { this.createDialog(this, 2243.10344827586, 4050, "No Jim, once I was thinking of dropping out and you visited me in a dream and your flowing hair spelled out the secrets of the universe to me in JavaScript", zone, "Why yes, I am the best", "Anyone would have done the same. It's nothing special", 'thanks', 'demure', false).setScrollFactor(0) },
	"thanks": function (zone) { this.createDialog(this, 2243.10344827586, 4050, "JATINDER stands aside to let you pass. He gives you A SELF CONFIDENCE BOOST", zone, 'continue', "", null, null, true).setScrollFactor(0) },
}

export default scenarioTree;